# Generated by Django 4.1.2 on 2022-11-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0002_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='price',
            new_name='wage',
        ),
    ]
