# Generated by Django 4.1.2 on 2022-12-15 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0003_rename_price_work_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('images', models.ImageField(blank=True, upload_to='images/')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Work.work')),
            ],
        ),
    ]
