# Generated by Django 4.1.2 on 2022-12-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0005_rename_work_images_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
