# Generated by Django 4.1.2 on 2022-12-18 11:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0008_alter_images_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
