# Generated by Django 4.1.2 on 2022-12-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0011_remove_category_level_remove_category_lft_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='image_tag',
        ),
    ]
