# Generated by Django 4.1.2 on 2022-12-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0012_rename_images_images_image_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image_tag',
            new_name='images',
        ),
    ]
