# Generated by Django 4.1.2 on 2022-12-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0015_rename_image_images_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='gmail',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
