# Generated by Django 4.1.2 on 2022-12-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0016_work_gmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='gmail',
            field=models.CharField(max_length=200),
        ),
    ]
