# Generated by Django 4.1.2 on 2022-12-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0017_alter_work_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='facebook',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='work',
            name='instagram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='work',
            name='linkedin',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
