# Generated by Django 4.1.2 on 2022-12-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0018_work_facebook_work_instagram_work_linkedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='instagram',
            new_name='twitter',
        ),
    ]
