# Generated by Django 4.1.2 on 2022-12-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0019_rename_instagram_work_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='facebook',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='work',
            name='twitter',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
