# Generated by Django 4.1.2 on 2022-12-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_setting_aboutus_alter_setting_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='contact_map',
            field=models.CharField(max_length=500),
        ),
    ]
